services:
  demomessage.api:
    image: ${DOCKER_REGISTRY-}demomessage.api
    container_name: demomessage.api
    build:
      context: .
      dockerfile: DemoMessage.Api/Dockerfile
    environment:
      - RABBITMQ__HOST=amqp://rabbitmq:5672
      - RABBITMQ__Username=guest
      - RABBITMQ__Password=guest
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - "5000:8080"
      
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  
  seq:
    image: datalust/seq:latest
    volumes:
      - ./.containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  sampleelasticsearch:
    image: sampleelasticsearch
    build:
      context: .
      dockerfile: SampleElasticSearch/Dockerfile
